#!/bin/bash

# See http://c-ruttkies.github.io/MetFrag/projects/metfrag22cl/

#############
# CONSTANTS #
#############

SCRIPTDIR=$(dirname $0)

#########
# ERROR #
#########

function error {
	printf "ERROR: $1\n" >&2
	exit 1
}

####################
# GET OPTION VALUE #
####################

function get_opt_val {
	if [ -z "$2" ] ; then
		error "\"$1\" requires a non-empty option argument."
	fi
	echo $2
}

#############
# READ ARGS #
#############

function read_args {
	while true ; do
		case $1 in
			-f|--file) g_param_file=$(get_opt_val $1 $2) ; shift ;;
			--pubchem) g_db=PubChem ;;
			--kegg) g_db=KEGG ;;
			-s|--spectrum|--spectrum-file) g_spectrum_file=$(get_opt_val $1 $2) ; shift ;;
			-?*) error "Unknown option \"$1\"." ;;
			*) break
		esac
		shift
	done

	# Check parameters
	if [ -z "$g_param_file" ] ; then
		if [ -z "$g_spectrum_file" ] ; then error "You must specify a spectrum file through --spectrum option." ; fi
		if [ ! -f "$g_spectrum_file" ] ; then error "Cannot find the spectrum file \"$g_spectrum_file\"." ; fi
	fi
}

#####################
# CREATE PARAM FILE #
#####################

function create_param_file {
	cat >$g_param_file <<EOF
#	
# data file containing mz intensity peak pairs (one per line)	
#	
PeakListPath = $g_spectrum_file
#
# Database parameters -> how to retrieve candidates	
#	
MetFragDatabaseType = $g_db
NeutralPrecursorMolecularFormula = C9H11Cl3NO3PS	
NeutralPrecursorMass = 348.926284	
#	
# peak matching parameters	
#	
FragmentPeakMatchAbsoluteMassDeviation = 0.001	
FragmentPeakMatchRelativeMassDeviation = 5	
PrecursorIonMode = 1	
IsPositiveIonMode = True	
#	
# scoring parameters	
#	
MetFragScoreTypes = FragmenterScore	
MetFragScoreWeights = 1.0	
#	
# output	
# SDF, XLS, CSV, ExtendedXLS, ExtendedFragmentsXLS	
#	
MetFragCandidateWriter = CSV
SampleName = example1	
ResultsPath = .	
#	
# following parameteres can be kept as they are	
#	
MaximumTreeDepth = 2	
MetFragPreProcessingCandidateFilter = UnconnectedCompoundFilter	
MetFragPostProcessingCandidateFilter = InChIKeyFilter	
# NumberThreads = 1
EOF
}

################
# CALL METFRAG #
################

function call_metfrag {
	java -jar $SCRIPTDIR/MetFrag2.2-CL.jar $g_param_file
}

########
# MAIN #
########

read_args "$@"

if [ -z "$g_param_file" ] ; then
	g_param_file=$(mktemp -t metfrag.XXXXXX)
	create_param_file
	call_metfrag
	rm $g_param_file
else
	call_metfrag
fi
