#!/bin/bash

# See http://c-ruttkies.github.io/MetFrag/projects/metfrag22cl/

#############
# CONSTANTS #
#############

SCRIPTDIR=$(dirname $0)

MSPOS=pos
MSNEG=neg

DBPUBCHEM=pubchem
DBKEGG=kegg

OUTTYPECSV=csv
OUTTYPEXLS=xls

#########
# ERROR #
#########

function error {
	printf "ERROR: $1\n" >&2
	exit 1
}

####################
# GET OPTION VALUE #
####################

function get_opt_val {
	if [ -z "$2" ] ; then
		error "\"$1\" requires a non-empty option argument."
	fi
	echo $2
}

#############
# READ ARGS #
#############

function read_args {

	g_generate_param_file=yes
	g_keep_generated_param_file=

	while true ; do
		case $1 in
			-f|--file|--param-file) g_param_file=$(get_opt_val $1 $2) ; g_generate_param_file= ; shift ;;
			--output-param-file) g_param_file=$(get_opt_val $1 $2) ; g_keep_generated_param_file=yes ; shift ;;
			-d|--db|--database) g_db=$(get_opt_val $1 $2) ; shift ;;
			-m|--mode) g_mode=$(get_opt_val $1 $2) ; shift ;;
			-s|--spectrum|--spectrum-file) g_spectrum_file=$(get_opt_val $1 $2) ; shift ;;
			-o|--output-file) g_output_file=$(get_opt_val $1 $2) ; shift ;;
			-?*) error "Unknown option \"$1\"." ;;
			*) break
		esac
		shift
	done

	# Check parameters
	if [ -n "$g_generate_param_file" ] ; then
		[ -n "$g_db" ] || error "You must select a database through -d option."
		[ "$g_db" = "$DBPUBCHEM" -o "$g_db" = "$DBKEGG" ] || error "The database must be one of \"$DBKEGG\" or \"$DBPUBCHEM\"."
		[ -n "$g_spectrum_file" ] || error "You must specify a spectrum file through -s option."
		[ -f "$g_spectrum_file" ] || error "Cannot find the spectrum file \"$g_spectrum_file\"."
		[ -n "$g_mode" ] || error "You must specify an MS mode through -m option."
		[ "$g_mode" = "$MSPOS" -o "$g_mode" = "$MSNEG" ] || error "MS mode must be either \"$MSPOS\" or \"$MSNEG\"."

		# Output file
		[ -n "$g_output_file" ] || error "You must specify an output file through -o option."
		if [ -z "$g_output_type" ] ; then
			ext=${g_output_file##*.}
			case $ext in
				csv|CSV) g_output_type=$OUTTYPECSV ;;
				xls|XLS) g_output_type=$OUTTYPEXLS ;;
				*) error "Unknown extension \"$ext\" for output file \"$g_output_file\"."
			esac
		fi
		[ -n "$g_output_type" ] || error "You must specify an output file type through -t option."
		[ "$g_output_type" = "$OUTTYPECSV" -o "$g_output_type" = "$OUTTYPEXLS" ] || error "The output type must be one of \"$OUTTYPECSV\" or \"$OUTTYPEXLS\"."
	fi
}

#####################
# CREATE PARAM FILE #
#####################

function create_param_file {

# Get database tag
case $g_db in
	$DBPUBCHEM) database=PubChem ;;
	$DBKEGG) database=KEGG ;;
esac

# Get mode tag
case $g_mode in
	$MSPOS) mode=True ;;
	$MSNEG) mode=False ;;
esac

# Get writer tag
case $g_output_type in
	$OUTTYPECSV) writer=CSV ;;
	$OUTTYPEXLS) writer=XLS ;;
esac

# Output file
output_file_name=$(basename "$g_output_tmp_file")
output_file_dir=$(dirname "$g_output_tmp_file")
case $g_output_type in
	$OUTTYPECSV) g_output_tmp_file="$g_output_tmp_file.csv" ;;
	$OUTTYPEXLS) g_output_tmp_file="$g_output_tmp_file.xls" ;;
esac

	cat >$g_param_file <<EOF
#	
# data file containing mz intensity peak pairs (one per line)	
#	
PeakListPath = $g_spectrum_file
#
# Database parameters -> how to retrieve candidates	
#	
MetFragDatabaseType = $database
NeutralPrecursorMolecularFormula = C9H11Cl3NO3PS	
NeutralPrecursorMass = 348.926284	
#	
# peak matching parameters	
#	
FragmentPeakMatchAbsoluteMassDeviation = 0.001	
FragmentPeakMatchRelativeMassDeviation = 5	
PrecursorIonMode = 1	
IsPositiveIonMode = $mode
#	
# scoring parameters	
#	
MetFragScoreTypes = FragmenterScore	
MetFragScoreWeights = 1.0	
#	
# output	
# SDF, XLS, CSV, ExtendedXLS, ExtendedFragmentsXLS	
#	
MetFragCandidateWriter = $writer
SampleName = $output_file_name
ResultsPath = $output_file_dir
#	
# following parameteres can be kept as they are	
#	
MaximumTreeDepth = 2	
MetFragPreProcessingCandidateFilter = UnconnectedCompoundFilter	
MetFragPostProcessingCandidateFilter = InChIKeyFilter	
# NumberThreads = 1
EOF
}

################
# CALL METFRAG #
################

function call_metfrag {
	java -jar $SCRIPTDIR/MetFrag2.2-CL.jar $g_param_file
}

########
# MAIN #
########

read_args "$@"

# Create output temp file
g_output_tmp_file=$(mktemp -t metfrag.output.XXXXXX)

if [ -n "$g_generate_param_file" ] ; then
	[ -n "$g_param_file" ] || g_param_file=$(mktemp -t metfrag.XXXXXX)
	create_param_file
	call_metfrag
	[ -z "$g_keep_generated_param_file" ] && rm $g_param_file
else
	call_metfrag
fi

# Rename output temp file
mv $g_output_tmp_file $g_output_file
